wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1633963711
    t:
      1:
      - 1
      4: 3.9.6
      5: 0.12.1
      8:
      - 1
      - 3
      - 5
