wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1634118377
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.9.6
      5: 0.12.1
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 5
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 1.0e-07
